server:
  port: 8008
spring:
  application:
    name: service-acl
  datasource:
    password: root
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli_edu?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    host: 192.168.80.132
    database: 0
    port: 6379
    timeout: 180000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848  #注册中心
mybatis-plus:
  mapper-locations: classpath:com/gx/serviceacl/mapper/xml/*.xml