server:
  port: 8005
spring:
  application:
    name: service-msm
  redis:
    host: 192.168.80.132
    port: 6379
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0
  jackson:
    date-format: yyyyMMdd HH:mm:ss
    time-zone: GMT+8
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  profiles:
    active: dev
ali:
  yun:
    access-key-id: LTAI5tHzwCybBftRKLJzVAqG
    access-key-secret: mzybEb7Gvpnx6hArmJe2LzEA1A6JXV
    template-code: SMS_154950909
    sign-name: 阿里云短信测试