server:
  port: 8007
spring:
  profiles:
    active: dev
  application:
    name: service-statistics
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/guli_edu?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1
mybatis-plus:
  mapper-locations: classpath:com/gx/staservice/mapper/xml/*.xml
feign:
  hystrix:
    enabled: true #feign开启熔断
# 设置hystrix超时时间，默认1000ms
    command:
      default:
        execution:
          isolation:
            thread:
              timeoutInMilliseconds: 3000


